kind: Pod
apiVersion: v1
metadata:
  name: annotations
  annotations:
    imageregistry: "https://hub.docker.com/"
    buildURL: "https://jenkins.devops.com/target/backend/build/67"
spec:
  containers:
  - name: nginx
    image: nginx



# 54.152.103.126 | 172.31.88.42 | t3.micro | https://github.com/suprajaspace/01.k8-resources.git
# [ ec2-user@ip-172-31-88-42 ~/01.k8-resources ]$ kubectl apply -f 05-annotations.yaml
# pod/annotations created

# 54.152.103.126 | 172.31.88.42 | t3.micro | https://github.com/suprajaspace/01.k8-resources.git
# [ ec2-user@ip-172-31-88-42 ~/01.k8-resources ]$ kubectl get pods
# NAME              READY   STATUS    RESTARTS   AGE
# annotations       1/1     Running   0          7s
# labels            1/1     Running   0          3m3s
# multi-container   2/2     Running   0          8m55s
# nginx             1/1     Running   0          21m

# 54.152.103.126 | 172.31.88.42 | t3.micro | https://github.com/suprajaspace/01.k8-resources.git
# [ ec2-user@ip-172-31-88-42 ~/01.k8-resources ]$ kubectl describe pod annotations
# Name:             annotations
# Namespace:        default
# Priority:         0
# Service Account:  default
# Node:             ip-192-168-48-125.ec2.internal/192.168.48.125
# Start Time:       Sat, 28 Dec 2024 04:10:33 +0000
# Labels:           <none>
# Annotations:      buildURL: https://jenkins.devops.com/target/backend/build/67
#                   imageregistry: https://hub.docker.com/
# Status:           Running
# IP:               192.168.49.95
# IPs:
#   IP:  192.168.49.95
# Containers:
#   nginx:
#     Container ID:   containerd://fae089a3db90885df2d0832aeb87b489c6432edf69b0d15894493447c8e0fcfa
#     Image:          nginx
#     Image ID:       docker.io/library/nginx@sha256:42e917aaa1b5bb40dd0f6f7f4f857490ac7747d7ef73b391c774a41a8b994f15
#     Port:           <none>
#     Host Port:      <none>
#     State:          Running
#       Started:      Sat, 28 Dec 2024 04:10:34 +0000
#     Ready:          True
#     Restart Count:  0
#     Environment:    <none>
#     Mounts:
#       /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-xvf6s (ro)
# Conditions:
#   Type                        Status
#   PodReadyToStartContainers   True
#   Initialized                 True
#   Ready                       True
#   ContainersReady             True
#   PodScheduled                True
# Volumes:
#   kube-api-access-xvf6s:
#     Type:                    Projected (a volume that contains injected data from multiple sources)
#     TokenExpirationSeconds:  3607
#     ConfigMapName:           kube-root-ca.crt
#     ConfigMapOptional:       <nil>
#     DownwardAPI:             true
# QoS Class:                   BestEffort
# Node-Selectors:              <none>
# Tolerations:                 node.kubernetes.io/not-ready:NoExecute op=Exists for 300s
#                              node.kubernetes.io/unreachable:NoExecute op=Exists for 300s
# Events:
#   Type    Reason     Age   From               Message
#   ----    ------     ----  ----               -------
#   Normal  Scheduled  46s   default-scheduler  Successfully assigned default/annotations to ip-192-168-48-125.ec2.internal
#   Normal  Pulling    45s   kubelet            Pulling image "nginx"
#   Normal  Pulled     45s   kubelet            Successfully pulled image "nginx" in 123ms (123ms including waiting). Image size: 72099410 bytes.
#   Normal  Created    45s   kubelet            Created container nginx
#   Normal  Started    45s   kubelet            Started container nginx

